version: '3.8'

services:
  frontend:
    build: .
    command: python leaderboard/app.py
    ports:
      - "5000:5000"
    volumes:
      - ./leaderboard/auth:/app/credentials
      - ./leaderboard/uploads:/app/leaderboard/uploads
    env_file:
      - .env.docker
    environment:
      - GCS_CREDENTIALS_PATH=/app/credentials/aitrainer-20250418-e220169904a0.json
      - PORT=5000
      - HOST=0.0.0.0
    depends_on:
      - inference
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/"]
      interval: 30s
      timeout: 10s
      retries: 3

  inference:
    build: .
    command: python leaderboard/inference_service.py
    ports:
      - "5001:5001"
    volumes:
      - ./leaderboard/auth:/app/credentials
      - ./leaderboard/uploads:/app/leaderboard/uploads
    env_file:
      - .env.docker
    environment:
      - GCS_CREDENTIALS_PATH=/app/credentials/aitrainer-20250418-e220169904a0.json
      - INFERENCE_PORT=5001
      - INFERENCE_HOST=0.0.0.0
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001/health"]
      interval: 30s
      timeout: 10s
      retries: 3